# Generated by Django 5.1.4 on 2025-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='flags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='revealed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(),
        ),
    ]
