# Generated by Django 5.1.4 on 2025-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_game_flags_game_game_over_game_revealed_game_won_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=list),
        ),
    ]
