# Generated by Django 5.1.4 on 2025-01-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_game_score_alter_game_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
